In [33]:
import pandas as pd

In [34]:
data=pd.read_csv("D:/Extract here/student_10.csv")

In [35]:
data

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [36]:
data.info()    #shape-rows & column,non-value,datatype

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        10 non-null     str
 1   Student ID  7 non-null      float64
 2   Class       10 non-null     int64
 3   Study hrs   8 non-null      float64
 4   Percentage  7 non-null      float64
dtypes: float64(3), int64(1), str(1)
memory usage: 532.0 bytes

In [37]:
data.describe()       #stastical analysis(mean,median,min,max,outlier hai ya nahi)

        Student ID      Class  Study hrs  Percentage
count     7.000000  10.000000   8.000000    7.000000
mean   1006.000000  11.100000   4.375000   72.142857
std       3.464102   0.875595   3.020761   15.236235
min    1001.000000  10.000000   0.000000   50.000000
25%    1003.500000  10.250000   2.750000   60.000000
50%    1007.000000  11.000000   4.000000   80.000000
75%    1008.500000  12.000000   6.000000   82.500000
max    1010.000000  12.000000  10.000000   90.000000

In [38]:
data.shape    #to check rows and column (rows,column)

(10, 5)

In [39]:
type(data)

pandas.DataFrame

In [40]:
data.size

50

In [41]:
data.head()   #by default 5 records print karega

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN

In [42]:
data.head(3)

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0

In [43]:
data.tail()

         Date  Student ID  Class  Study hrs  Percentage
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [44]:
  data.isna() #every colume mai kitne null value hai

    Date  Student ID  Class  Study hrs  Percentage
0  False       False  False      False       False
1  False       False  False      False       False
2  False        True  False      False       False
3  False        True  False      False        True
4  False       False  False      False        True
5  False        True  False      False        True
6  False       False  False      False       False
7  False       False  False       True       False
8  False       False  False       True       False
9  False       False  False      False       False

In [45]:
  data.isna().sum()    #only true values ki summation karega

Date          0
Student ID    3
Class         0
Study hrs     2
Percentage    3
dtype: int64

In [62]:
data.dropna()    #remove null value(rowes)  orignal mai change nahi karta

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
6  09-07-2021      1007.0     12        4.0        80.0
9  12-07-2021      1010.0     12        6.0        85.0

In [47]:
data.dropna(axis=1)

         Date  Class
0  01-07-2021     10
1  02-07-2021     10
2  03-07-2021     10
3  06-07-2021     11
4  07-07-2021     11
5  08-07-2021     11
6  09-07-2021     12
7  10-07-2021     12
8  11-07-2021     12
9  12-07-2021     12

In [48]:
data.dropna(inplace=True,axis=1)     #origanl mai changes hotd hai
data

         Date  Class
0  01-07-2021     10
1  02-07-2021     10
2  03-07-2021     10
3  06-07-2021     11
4  07-07-2021     11
5  08-07-2021     11
6  09-07-2021     12
7  10-07-2021     12
8  11-07-2021     12
9  12-07-2021     12

In [49]:
data=pd.read_csv("D:/Extract here/student_10.csv")
data

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [50]:
data.isna().sum()

Date          0
Student ID    3
Class         0
Study hrs     2
Percentage    3
dtype: int64

In [51]:
data['Class']   #to asses one column

0    10
1    10
2    10
3    11
4    11
5    11
6    12
7    12
8    12
9    12
Name: Class, dtype: int64

In [52]:
data['Class'].mean()

np.float64(11.1)

In [53]:
data['Class'].sum()

np.int64(111)

In [54]:
data['Class'].unique()    #to check unique values

array([10, 11, 12])

In [55]:
data['Class'].value_counts()     # return count of unique valuess

Class
12    4
10    3
11    3
Name: count, dtype: int64

In [56]:
data.columns

Index(['Date', 'Student ID', 'Class', 'Study hrs', 'Percentage'], dtype='str')

In [57]:
data['Study hrs']

0     2.0
1     6.0
2     3.0
3     0.0
4     4.0
5    10.0
6     4.0
7     NaN
8     NaN
9     6.0
Name: Study hrs, dtype: float64

In [58]:
data['Study hrs']>4.0

0    False
1     True
2    False
3    False
4    False
5     True
6    False
7    False
8    False
9     True
Name: Study hrs, dtype: bool

In [59]:
data[data['Study hrs']>4.0]   #data[condition]  condition T rahi wo hi record print karega         # Filtering technique

         Date  Student ID  Class  Study hrs  Percentage
1  02-07-2021      1002.0     10        6.0        80.0
5  08-07-2021         NaN     11       10.0         NaN
9  12-07-2021      1010.0     12        6.0        85.0

In [60]:
df2=data[data['Study hrs']>4.0]
df2

         Date  Student ID  Class  Study hrs  Percentage
1  02-07-2021      1002.0     10        6.0        80.0
5  08-07-2021         NaN     11       10.0         NaN
9  12-07-2021      1010.0     12        6.0        85.0

In [61]:
data['Study hrs'].agg(['min','max','sum'])

min     0.0
max    10.0
sum    35.0
Name: Study hrs, dtype: float64