In [79]:
import pandas as pd

In [80]:
df2=pd.DataFrame({'ID':[101,102,103],
                  'NAME':['Vedika','Amisha','Kartik'],
                  'SALARY':[3000,2500,200]})
df2

    ID    NAME  SALARY
0  101  Vedika    3000
1  102  Amisha    2500
2  103  Kartik     200

In [81]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      3 non-null      int64
 1   NAME    3 non-null      str
 2   SALARY  3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes

In [82]:
df2.describe()

          ID       SALARY
count    3.0     3.000000
mean   102.0  1900.000000
std      1.0  1493.318452
min    101.0   200.000000
25%    101.5  1350.000000
50%    102.0  2500.000000
75%    102.5  2750.000000
max    103.0  3000.000000

In [83]:
df2['ID']

0    101
1    102
2    103
Name: ID, dtype: int64

In [84]:
df2[df2['SALARY']>2000]

    ID    NAME  SALARY
0  101  Vedika    3000
1  102  Amisha    2500

In [85]:
df2.loc[df2['SALARY'] < 2500, 'SALARY']= 10000  #change into orignal location
df2

    ID    NAME  SALARY
0  101  Vedika    3000
1  102  Amisha    2500
2  103  Kartik   10000

In [86]:
df2.loc[[0,2]]

    ID    NAME  SALARY
0  101  Vedika    3000
2  103  Kartik   10000

In [87]:
df2.loc[[0,2],'SALARY']

0     3000
2    10000
Name: SALARY, dtype: int64

In [88]:
df2.loc[[0,2],['NAME','SALARY']]

     NAME  SALARY
0  Vedika    3000
2  Kartik   10000

In [89]:
df2.loc[[True,False,True]]

    ID    NAME  SALARY
0  101  Vedika    3000
2  103  Kartik   10000

In [90]:
df2.iloc[:,0]

0    101
1    102
2    103
Name: ID, dtype: int64

In [91]:
df2.iloc[:, 0:2]

    ID    NAME
0  101  Vedika
1  102  Amisha
2  103  Kartik

In [92]:
df2.iloc[0]

ID           101
NAME      Vedika
SALARY      3000
Name: 0, dtype: object

In [93]:
df2.iloc[:,[0,2]]   #work on indexing

    ID  SALARY
0  101    3000
1  102    2500
2  103   10000

In [94]:
df2

    ID    NAME  SALARY
0  101  Vedika    3000
1  102  Amisha    2500
2  103  Kartik   10000

In [95]:
df2.replace({10000:12000,3000:3200})

    ID    NAME  SALARY
0  101  Vedika    3200
1  102  Amisha    2500
2  103  Kartik   12000

In [96]:
df2

    ID    NAME  SALARY
0  101  Vedika    3000
1  102  Amisha    2500
2  103  Kartik   10000

In [97]:
df2['SALARY'].replace({10000:12000,3000:3200})

0     3200
1     2500
2    12000
Name: SALARY, dtype: int64

In [98]:
df2['SALARY']=df2['SALARY'].replace({10000:12000,3000:3200})
df2

    ID    NAME  SALARY
0  101  Vedika    3200
1  102  Amisha    2500
2  103  Kartik   12000

In [99]:
df2['Address']=['Pune','Mumbai','Warora']
df2

    ID    NAME  SALARY Address
0  101  Vedika    3200    Pune
1  102  Amisha    2500  Mumbai
2  103  Kartik   12000  Warora

In [100]:
df2.insert(1, 'AGE',[21,22,21])
df2

    ID  AGE    NAME  SALARY Address
0  101   21  Vedika    3200    Pune
1  102   22  Amisha    2500  Mumbai
2  103   21  Kartik   12000  Warora

In [101]:
len(df2)

3

In [102]:
df2.loc[len(df2)]=[104,20,'Ashawini',4000,'Nagpur']
df2

    ID  AGE      NAME  SALARY Address
0  101   21    Vedika    3200    Pune
1  102   22    Amisha    2500  Mumbai
2  103   21    Kartik   12000  Warora
3  104   20  Ashawini    4000  Nagpur

In [105]:
df2.loc[df2['ID']==102,'SALARY']=8000
df2

    ID  AGE      NAME  SALARY Address
0  101   21    Vedika    3200    Pune
1  102   22    Amisha    8000  Mumbai
2  103   21    Kartik   12000  Warora
3  104   20  Ashawini    4000  Nagpur

In [109]:
df2[df2['AGE']>20]['NAME']

0    Vedika
1    Amisha
2    Kartik
Name: NAME, dtype: str

In [111]:
df2.loc[df2['AGE']>20,'NAME']

0    Vedika
1    Amisha
2    Kartik
Name: NAME, dtype: str

In [114]:
df2[(df2['AGE']>20)&(df2['SALARY']>2000)]

    ID  AGE    NAME  SALARY Address
0  101   21  Vedika    3200    Pune
1  102   22  Amisha    8000  Mumbai
2  103   21  Kartik   12000  Warora

In [115]:
df2

    ID  AGE      NAME  SALARY Address
0  101   21    Vedika    3200    Pune
1  102   22    Amisha    8000  Mumbai
2  103   21    Kartik   12000  Warora
3  104   20  Ashawini    4000  Nagpur

In [116]:
df2.drop(2)    #remove row

    ID  AGE      NAME  SALARY Address
0  101   21    Vedika    3200    Pune
1  102   22    Amisha    8000  Mumbai
3  104   20  Ashawini    4000  Nagpur

In [117]:
df2.drop([0,2,3])

    ID  AGE    NAME  SALARY Address
1  102   22  Amisha    8000  Mumbai

In [118]:
df2.drop('AGE',axis=1)    #remove column

    ID      NAME  SALARY Address
0  101    Vedika    3200    Pune
1  102    Amisha    8000  Mumbai
2  103    Kartik   12000  Warora
3  104  Ashawini    4000  Nagpur

In [119]:
df2.drop(['ID','Address'],axis=1)

   AGE      NAME  SALARY
0   21    Vedika    3200
1   22    Amisha    8000
2   21    Kartik   12000
3   20  Ashawini    4000

In [120]:
data=pd.read_csv("D:/Extract here/student_10.csv")
data

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [121]:
data.isna().sum()

Date          0
Student ID    3
Class         0
Study hrs     2
Percentage    3
dtype: int64

In [123]:
data.dropna()

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
6  09-07-2021      1007.0     12        4.0        80.0
9  12-07-2021      1010.0     12        6.0        85.0

In [125]:
data.dropna(axis=1)

         Date  Class
0  01-07-2021     10
1  02-07-2021     10
2  03-07-2021     10
3  06-07-2021     11
4  07-07-2021     11
5  08-07-2021     11
6  09-07-2021     12
7  10-07-2021     12
8  11-07-2021     12
9  12-07-2021     12

In [126]:
  # replace null valu
#numeric valu ko replace krne ke liye -mean, median valu     kyuki effect nahi pdna chahiye caclulation mai
#text data- categorical- mode(most accored element or mazimun valu)

In [127]:
mean=data['Study hrs'].mean()
mean

np.float64(4.375)

In [128]:
data['Study hrs'].fillna(mean)

0     2.000
1     6.000
2     3.000
3     0.000
4     4.000
5    10.000
6     4.000
7     4.375
8     4.375
9     6.000
Name: Study hrs, dtype: float64

In [129]:
data.bfill()

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021      1005.0     10        3.0        60.0
3  06-07-2021      1005.0     11        0.0        80.0
4  07-07-2021      1005.0     11        4.0        80.0
5  08-07-2021      1007.0     11       10.0        80.0
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        6.0        90.0
8  11-07-2021      1009.0     12        6.0        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [130]:
data.ffill()

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021      1002.0     10        3.0        60.0
3  06-07-2021      1002.0     11        0.0        60.0
4  07-07-2021      1005.0     11        4.0        60.0
5  08-07-2021      1005.0     11       10.0        60.0
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        4.0        90.0
8  11-07-2021      1009.0     12        4.0        60.0
9  12-07-2021      1010.0     12        6.0        85.0